/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.mavenproject1.models.MedicineModel;
import com.mycompany.mavenproject1.models.UserModel;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arshvir
 */
public class BuyMedicine extends javax.swing.JFrame {
    static UserModel userModel = new UserModel();
    private SingletonClass singletonClass = SingletonClass.getInstance();
    String searchKey = "";
    ArrayList<MedicineModel> medicineArray = new ArrayList<MedicineModel>();
    int empId = -1;
    MedicineModel selectedMedicine = new MedicineModel();

    /**
     * Creates new form BuyMedicine
     */
    public BuyMedicine() {
        initComponents();
    }
    
    public BuyMedicine(UserModel userModel) {
        empId = userModel.getId();
        initComponents();
    }
    
    private void updateCart(){
        String[] headers = {"Medicine Id", "Medicine Name","Company Name", "No. of Unit", "Price per Unit", "Total Price", "Genre"};
        DefaultTableModel dtm = new DefaultTableModel(null, headers);
        table.setModel(dtm);

        Object[] row = new Object[9];
        Double billTotal = 0.0;
        for(MedicineModel medicineModel : medicineArray){

                row[0] = medicineModel.getMedicineId();
                row[1] = medicineModel.getMedicineName();
                row[2] = medicineModel.getCompany();
                //row[3] = medicineModel.getExpiryDate();
                row[3] = medicineModel.getSellingUnit();
                row[4] = medicineModel.getPricePerUnit();
                row[5] = medicineModel.getSellingUnit();
                row[6] = medicineModel.getGenre();
                Double total = medicineModel.getSellingUnit() * medicineModel.getPricePerUnit();
                row[5] = total.toString();
                billTotal += total;
                dtm.addRow(row);

        }  
        lblBillTotal.setText("RS "+String.valueOf(billTotal));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        searchMedicineTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        pricePerUnit = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        medicineName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        company = new javax.swing.JTextPane();
        LblPhone = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        genre = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        sellUnits = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        totalPrice = new javax.swing.JTextPane();
        addToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblBillTotal = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTextField2.setText("Search Medicine");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        searchMedicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "name", "genre"
            }
        ));
        searchMedicineTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMedicineTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(searchMedicineTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Company Name");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Medicine Name");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Price per unit");

        jScrollPane7.setViewportView(pricePerUnit);

        jScrollPane3.setViewportView(medicineName);

        jScrollPane2.setViewportView(company);

        LblPhone.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        LblPhone.setText("Genre");

        jScrollPane6.setViewportView(genre);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setText("No. of units");

        sellUnits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sellUnitsKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(sellUnits);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Total Price");

        totalPrice.setEditable(false);
        totalPrice.setAutoscrolls(false);
        jScrollPane8.setViewportView(totalPrice);

        addToCart.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        addToCart.setText("Add To cart");
        addToCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartMouseClicked(evt);
            }
        });
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine Id", "Name", "Company Name", "Price per unit", "No. of unit", "Total Price", "Genre"
            }
        ));
        jScrollPane1.setViewportView(table);

        lblBillTotal.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        lblBillTotal.setText("Rs ");

        print.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        print.setText("Buy and Print");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Buy Medicine");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sell Medicines - Copy.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(23, 23, 23)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(LblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(23, 23, 23)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(jScrollPane6)))))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(addToCart)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(lblBillTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(print)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LblPhone))
                                    .addGap(7, 7, 7)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addToCart)))
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(print)
                    .addComponent(lblBillTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:

        // String keyType = evt.getKeyChar().toString();
        char c = evt.getKeyChar();
        System.out.println("c "+c);

        searchKey = searchKey +String.valueOf(c);
        System.out.println("searchKey "+searchKey);
        if (searchKey.isEmpty() == false) {
            searchKey = searchKey.trim();
            try {
                System.out.println("in condition");
                String selectStatement = "SELECT * FROM addmedicine WHERE medicineName LIKE ?";
                PreparedStatement preparedStatement = singletonClass.connection.prepareStatement(selectStatement);
                preparedStatement.setString(1, "%"+searchKey+"%");
                ResultSet rs = preparedStatement.executeQuery();
                //  table.setModel(DbUtils.resultSetToTableModel(rs));
                String[] rowNames = {"id", "medicineName"};
                DefaultTableModel model = new DefaultTableModel(null, rowNames);
                searchMedicineTable.setModel(model);
                Object[] row = new Object[2];
                //  ArrayList<AddPatient> patient = new ArrayList<>();

                while (rs.next()) {
                    row[0] = rs.getInt(1);
                    row[1] = rs.getString("medicineName");
                    model.addRow(row);
                    //  SellMedicine.add(new SellMedicine(rs.getString(1),rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5) , rs.getString(6) , rs.getString(7)));
                }
                //SpinnerListModel spinner = new SpinnerListModel(userModel );

                // spinner.setModel(model);
            } catch (SQLException sqlException) {
                System.out.println("in exception line 528 " + sqlException.getMessage());
            }
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void searchMedicineTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMedicineTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dfm = (DefaultTableModel)searchMedicineTable.getModel();
        int seletedRow = searchMedicineTable.getSelectedRow();
        String id = dfm.getValueAt(seletedRow, 0).toString();
        try {
            System.out.println("in condition");
            String selectStatement = "SELECT * FROM addmedicine WHERE id = ?";
            PreparedStatement preparedStatement = singletonClass.connection.prepareStatement(selectStatement);
            preparedStatement.setString(1, id);
            ResultSet rs = preparedStatement.executeQuery();

            while (rs.next()) {

                selectedMedicine.setId(Integer.parseInt(String.valueOf(rs.getInt(1))));
                selectedMedicine.setCompany(rs.getString("company"));
                //selectedMedicine.setExpiryDate(rs.getString("expiryDate"));
                selectedMedicine.setGenre(rs.getString("genre"));
                selectedMedicine.setMedicineId(rs.getString("medicineId"));
                //selectedMedicine.setMfdDate(rs.getString("mfgDate"));
                selectedMedicine.setMedicineName(rs.getString("medicineName"));
                //selectedMedicine.setQuantity(Integer.parseInt(rs.getString("quantity")));
                selectedMedicine.setPricePerUnit(Double.parseDouble(rs.getString("pricePerUnit")));
                selectedMedicine.setSellingUnit(1);
                updateMedicineInfo();
            }

        } catch (SQLException sqlException) {
            System.out.println("in exception 631" + sqlException.getMessage());
        }
    }//GEN-LAST:event_searchMedicineTableMouseClicked

    private void updateMedicineInfo(){
        company.setText(selectedMedicine.getCompany());
        genre.setText(String.valueOf(selectedMedicine.getGenre()));
        //expiryDate.setText(String.valueOf(selectedMedicine.getexpiryDate()));
        
        medicineName.setText(selectedMedicine.getMedicineName());
//        availableUnits.setText(String.valueOf(selectedMedicine.getQuantity()));
        pricePerUnit.setText(String.valueOf(selectedMedicine.getPricePerUnit()));
  //      mfgDate.setText(selectedMedicine.getMfdDate());
        sellUnits.setText(String.valueOf(selectedMedicine.getSellingUnit()));
        Double total = selectedMedicine.getSellingUnit() * selectedMedicine.getPricePerUnit();
        totalPrice.setText(total.toString());
                    
    }
    
    private void sellUnitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellUnitsKeyTyped
        // TODO add your handling code here:
        //        char c = evt.getKeyChar();
        //        System.out.println("c "+c);
        //        int selectedQuantity =  c;
        //        System.out.println("selectedMedicine.getQuantity() "+selectedMedicine.getQuantity());
        //        System.out.println("selectedQuantity "+selectedQuantity);
        //        if(selectedQuantity > selectedMedicine.getQuantity()){
            //            sellUnits.setText("0");
            //        }else{
            //            double price = selectedQuantity * selectedMedicine.getPricePerUnit();
            //            totalPrice.setText(String.valueOf(price));
            //        }
    }//GEN-LAST:event_sellUnitsKeyTyped

    private void addToCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartMouseClicked
        // TODO add your handling code here:
        if (company.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Enter name");
        } else if (genre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "enter your id");
        } else if (medicineName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "enter Company Name");
        } //else if (availableUnits.getText().isEmpty()) {
           // JOptionPane.showMessageDialog(rootPane, "enter Number of Units");
        //} 
        else if (pricePerUnit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "enter Price Per Units");
        } else if (totalPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "enter Total Price");
        } else {
            String insertInDB = "SELECT * FROM addMedicine where id = ?";

            try {
                PreparedStatement prepareStatement = singletonClass.connection.prepareCall(insertInDB);

                prepareStatement.setInt(1 ,selectedMedicine.getId());
                ResultSet rs = prepareStatement.executeQuery();
                MedicineModel addtoCartModel = new MedicineModel();
                while (rs.next()) {
                    addtoCartModel.setId(Integer.parseInt(String.valueOf(rs.getInt(1))));
                    addtoCartModel.setCompany(rs.getString("company"));
                    //addtoCartModel.setExpiryDate(rs.getString("expiryDate"));
                    addtoCartModel.setGenre(rs.getString("genre"));
                    addtoCartModel.setMedicineId(rs.getString("medicineId"));
                    //addtoCartModel.setMfdDate(rs.getString("mfgDate"));
                    addtoCartModel.setMedicineName(rs.getString("medicineName"));
                    //addtoCartModel.setQuantity(Integer.parseInt(rs.getString("quantity")));
                    addtoCartModel.setPricePerUnit(Double.parseDouble(pricePerUnit.getText().toString()));
                    addtoCartModel.setSellingUnit(Integer.valueOf(sellUnits.getText().toString()));

                    medicineArray.add(addtoCartModel);
                    clearView();
                    updateCart();
                }

            } catch (SQLException sqlException) {
                System.out.println("in exception array " + sqlException.getMessage());

            }
        }
    }//GEN-LAST:event_addToCartMouseClicked

      private void clearView(){
        selectedMedicine = new MedicineModel();
        medicineName.setText("");
        //availableUnits.setText("");
        pricePerUnit.setText("");
        sellUnits.setText("");
        totalPrice.setText("");
       // mfgDate.setText("");
        
    }
    
    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToCartActionPerformed

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
        if(medicineArray.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Add medicines to cart");
        } else {
            String insertInDB = "INSERT INTO orderTable(customerName, customerPhone, total) VALUES(?,?,?)";
            try {
                PreparedStatement prepareStatement = singletonClass.connection.prepareCall(insertInDB);
                String generatedColumns[] = { "id" };
                prepareStatement.setString(1 ,company.getText().toString());
                prepareStatement.setString(2,genre.getText().toString());
                prepareStatement.setString(3, "22.3");
                int affectedRows = prepareStatement.executeUpdate();
                ResultSet rs = prepareStatement.getGeneratedKeys();

                if (rs.next()) {
                    long id = rs.getLong(1);
                    System.out.println("Inserted ID -" + id); // display inserted record
                    for(MedicineModel medicineModel : medicineArray){
                        System.out.println("medicineModel.getSellingUnit() "+medicineModel.getSellingUnit() + " medicine id "+ medicineModel.getMedicineId());
                        String updateDb = "UPDATE addmedicine SET quantity = quantity-"+medicineModel.getSellingUnit() + " WHERE medicineId = "+medicineModel.getMedicineId();
                        PreparedStatement ps = singletonClass.connection.prepareCall(updateDb);
                        int isUpdated = ps.executeUpdate();
                        String addInOrder = "INSERT INTO sellMedicine(medicineId, medicineName, company , genre, units , pricePerUnit , totalPrice, orderId ) VALUES (?,?,?,?,?,?,?,?)";
                        PreparedStatement psAddOrder = singletonClass.connection.prepareCall(addInOrder);

                        psAddOrder.setInt(1, medicineModel.getId());
                        psAddOrder.setString(2, medicineModel.getMedicineName());
                        psAddOrder.setString(3, medicineModel.getCompany());
                        psAddOrder.setString(4, medicineModel.getGenre());
                        psAddOrder.setInt(5, medicineModel.getSellingUnit());
                        psAddOrder.setDouble(6, medicineModel.getPricePerUnit());
                        Double total = medicineModel.getSellingUnit() * medicineModel.getPricePerUnit();
                        psAddOrder.setDouble(7, total);
                        psAddOrder.setLong(8, id);
                        psAddOrder.execute();
                    }
                    JOptionPane.showMessageDialog(rootPane, "Thaank you, your order will arrive soon :)");
                    generateBill();

                }
            } catch (SQLException sqlException) {
                System.out.println("in exception 593" + sqlException.getMessage());
            }
        }
    }//GEN-LAST:event_printMouseClicked

    void generateBill(){
        javax.swing.JTextArea bill = new javax.swing.JTextArea();
          bill.setText(bill.getText() + "\tPharma A+                                      \n");
        bill.setText(bill.getText() + "***********************************************************************\n");
        bill.setText(bill.getText() + "\t pharmaAp.com\t");
        bill.setText(bill.getText() + "\n\t Address: Gurdaspur, Punjab, India  ");
        bill.setText(bill.getText() + "\n \twww.instagram.com/avarshvir ");
        bill.setText(bill.getText() + "\n \t ");
        bill.setText(bill.getText() + "\n*********************************************************************");
        bill.setText(bill.getText() + "\n***************************   BILL     ******************************");
        bill.setText(bill.getText() + "\n************************************************************************\n");

        bill.setText(bill.getText() + "PRODUCTS" + "\t" + "QTY" + "\t" + "PRICE" + "\t\n");
        bill.setText(bill.getText() + "*************************************************************************\n");
        bill.setText(bill.getText() + "Medicine Company Name : ");
        bill.setText(bill.getText() + company.getText().toString()+ "\n");
        bill.setText(bill.getText() + "Medicine Genre : ");
        bill.setText(bill.getText() + genre.getText().toString()+ "\n");
        bill.setText(bill.getText() + "*************************************************************************\n");

        for(MedicineModel medicineModel : medicineArray){ 
            String drugname = medicineModel.getMedicineName();
            String qty =  String.valueOf(medicineModel.getSellingUnit());
            String price = String.valueOf(medicineModel.getPricePerUnit());
            bill.setText(bill.getText() + drugname + "\t" + qty + "\t" + price + "\n");
        }
         bill.setText(bill.getText() + "\n");
        bill.setText(bill.getText() + "\t" + "GST = 13%" + "\t\n");
        bill.setText(bill.getText() + "\t" + "Total=" + "\t" + lblBillTotal.getText().toString() + "\t\n");
        bill.setText(bill.getText() + "\n*****************************************************************************");
        bill.setText(bill.getText() + "\n**************************        THANKU       *******************************\n");
        //bill.setText(bill.getText() + "\n************* ******   COME AGAIN   **********************************");

        try {
            bill.print();
        } catch (PrinterException ex) {
            System.out.println("in exception print "+ex.getMessage());
        }
        
    }
    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(empId>-1)
        {
            PatientDashboard patientDashboard = new PatientDashboard();
            patientDashboard.setVisible(true);
        } else{
            PatientDashboard patientDashboard = new PatientDashboard();
            patientDashboard.setVisible(true);
       }
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblPhone;
    private javax.swing.JButton addToCart;
    private javax.swing.JTextPane company;
    private javax.swing.JTextPane genre;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lblBillTotal;
    private javax.swing.JTextPane medicineName;
    private javax.swing.JTextPane pricePerUnit;
    private javax.swing.JButton print;
    private javax.swing.JTable searchMedicineTable;
    private javax.swing.JTextPane sellUnits;
    private javax.swing.JTable table;
    private javax.swing.JTextPane totalPrice;
    // End of variables declaration//GEN-END:variables
}


